packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/ai/*'
  - 'packages/mcp/*'
  - 'packages/agents/*'
  - 'packages/domain/*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  protobufjs: true
  '@swc/core': true
  '@nestjs/core': true
  '@scarf/scarf': true

minimumReleaseAgeExclude:
  - '@anthropic-ai/sdk@0.123.0'
